export const termsContent = {
  lastUpdated: "January 3, 2025",
  sections: [
    {
      title: "Agreement to Terms",
      content: `By downloading, accessing, or using the Poise mobile application ("App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.

These Terms constitute a legally binding agreement between you and Poise ("Company," "we," "us," or "our"). We reserve the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance of the modified Terms.`
    },
    {
      title: "Age Requirement",
      content: `**You must be at least 18 years old to use Poise.** By using the App, you represent and warrant that you are at least 18 years of age.

The App is designed for adults seeking assistance with dating communication. We do not knowingly provide services to anyone under the age of 18. If we learn that a user is under 18, we will immediately terminate their account and delete any associated data.

If you are using the App on behalf of a couple or group, all individuals must be at least 18 years old.`
    },
    {
      title: "Account Registration and Responsibilities",
      content: `**Account Creation:** To use certain features of the App, you must create an account using a valid email address and authenticate through our secure login system.

**Account Security:** You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately if you suspect unauthorized access to your account.

**Accurate Information:** You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate and complete.

**One Account Per Person:** Each individual may only maintain one active account. Couples using the App should each create their own account or share a single account with mutual consent.`
    },
    {
      title: "Subscription Terms",
      content: `**Subscription Plans:** Poise offers both free and paid subscription tiers. Paid subscriptions provide access to additional features including unlimited message generation, all conversation styles, and priority responses.

**Billing:** Subscriptions are billed through Apple's App Store. By purchasing a subscription, you agree to Apple's terms of service for in-app purchases.

**Auto-Renewal:** Paid subscriptions automatically renew at the end of each billing period (weekly, monthly, or annually) unless you cancel before the renewal date. Your payment method will be charged within 24 hours prior to the end of the current period.

**Cancellation:** You may cancel your subscription at any time through your Apple ID account settings. Cancellation will take effect at the end of the current billing period. No refunds are provided for partial subscription periods.

**Price Changes:** We reserve the right to change subscription prices. Price changes will be communicated in advance and will apply to subsequent billing periods.

**Free Trial:** If offered, free trials automatically convert to paid subscriptions unless cancelled before the trial period ends.`
    },
    {
      title: "AI-Generated Content Disclaimer",
      content: `**Nature of Service:** Poise uses artificial intelligence to generate suggested messages and conversation assistance. This content is generated by third-party AI providers based on the context and preferences you provide.

**No Guarantee of Results:** AI-generated suggestions are provided for informational and assistive purposes only. We do not guarantee that using our suggestions will result in successful conversations, dates, or relationships.

**User Responsibility:** You are solely responsible for reviewing, editing, and deciding whether to use any AI-generated content. You should always use your own judgment before sending any message.

**Accuracy:** While we strive for helpful and appropriate suggestions, AI-generated content may occasionally be inaccurate, inappropriate, or not suited to your specific situation. Always review suggestions before use.

**Third-Party AI Services:** Our App utilizes third-party AI services to generate content. By using the App, you acknowledge that your prompts and conversation context are processed by these services to generate suggestions.`
    },
    {
      title: "Prohibited Uses",
      content: `You agree NOT to use Poise for any of the following purposes:

**Illegal Activities:**
- Any activity that violates applicable local, state, national, or international law
- Harassment, stalking, or threatening behavior toward any individual
- Fraud, impersonation, or deceptive practices

**Harmful Content:**
- Generating sexually explicit, pornographic, or obscene content
- Creating content intended to harass, abuse, or harm others
- Generating content that promotes violence, hatred, or discrimination
- Creating content involving minors in any inappropriate context

**Minors:**
- Using the App if you are under 18 years of age
- Generating any content related to individuals under 18 years of age
- Using the App to communicate with individuals you know or suspect to be minors

**Platform Abuse:**
- Attempting to reverse engineer, decompile, or extract source code from the App
- Using automated systems or bots to access the App
- Interfering with or disrupting the App's infrastructure
- Circumventing any usage limits or access restrictions

**Misrepresentation:**
- Creating fake profiles or impersonating others
- Using the App to spread misinformation or deceptive content
- Misrepresenting your identity, age, or relationship status

Violation of these prohibited uses may result in immediate account termination without refund.`
    },
    {
      title: "Intellectual Property",
      content: `**Our Property:** The App, including its design, features, content, and underlying technology, is owned by Poise and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works based on the App without our express written permission.

**Your Content:** You retain ownership of any original content you create using the App. However, you grant us a non-exclusive, worldwide, royalty-free license to use, store, and process your content solely for the purpose of providing and improving our services.

**AI-Generated Content:** Messages and suggestions generated by our AI are provided for your personal use in dating communications. You may use this content freely in your personal conversations. We do not claim ownership of AI-generated content created for you.

**Feedback:** If you provide feedback, suggestions, or ideas about the App, you grant us the right to use such feedback without compensation or obligation to you.`
    },
    {
      title: "Privacy and Data",
      content: `Your privacy is important to us. Our collection, use, and protection of your personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.

By using the App, you consent to the collection, use, and sharing of your information as described in our Privacy Policy.

Key privacy points:
- We collect email and account information for authentication
- Conversation data is sent to AI providers to generate suggestions
- We do not sell your personal data to third parties
- You can request deletion of your data at any time`
    },
    {
      title: "Disclaimer of Warranties",
      content: `THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

We do not warrant that:
- The App will be uninterrupted, secure, or error-free
- AI-generated suggestions will be accurate, appropriate, or effective
- The App will meet your specific requirements or expectations
- Any errors or defects will be corrected

You use the App at your own risk. We are not responsible for any outcomes resulting from your use of AI-generated suggestions in your personal communications.`
    },
    {
      title: "Limitation of Liability",
      content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, POISE AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:

- Loss of profits, data, or goodwill
- Personal or emotional distress
- Failed relationships or missed opportunities
- Any damages arising from your use of or inability to use the App

OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM YOUR USE OF THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR $100, WHICHEVER IS GREATER.

Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above limitations may not apply to you.`
    },
    {
      title: "Indemnification",
      content: `You agree to indemnify, defend, and hold harmless Poise and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including reasonable attorneys' fees) arising from:

- Your use of the App
- Your violation of these Terms
- Your violation of any third-party rights
- Any content you submit or transmit through the App
- Your interactions with other individuals facilitated by the App`
    },
    {
      title: "Termination",
      content: `**Termination by You:** You may terminate your account at any time by deleting your account through the App settings or by contacting us at support@trypoise.app.

**Termination by Us:** We reserve the right to suspend or terminate your account at any time, with or without cause, and with or without notice. Reasons for termination may include:
- Violation of these Terms
- Violation of our prohibited uses policy
- Fraudulent, abusive, or illegal activity
- Extended periods of inactivity
- Request by law enforcement or government agencies

**Effect of Termination:** Upon termination, your right to use the App will immediately cease. We may delete your account data in accordance with our Privacy Policy. Termination does not entitle you to any refund of subscription fees.

**Survival:** Sections regarding intellectual property, disclaimers, limitation of liability, indemnification, and governing law shall survive termination.`
    },
    {
      title: "Governing Law and Disputes",
      content: `**Governing Law:** These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.

**Dispute Resolution:** Any disputes arising from these Terms or your use of the App shall first be attempted to be resolved through informal negotiation. If informal resolution is unsuccessful, disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.

**Class Action Waiver:** You agree to resolve any disputes with us on an individual basis and waive your right to participate in any class action lawsuit or class-wide arbitration.

**Venue:** For any disputes not subject to arbitration, you consent to exclusive jurisdiction and venue in the state and federal courts located in Delaware.`
    },
    {
      title: "Changes to Terms",
      content: `We reserve the right to modify these Terms at any time. When we make changes, we will:
- Update the "Last Updated" date at the top of these Terms
- Notify you through the App or via email for material changes
- Provide reasonable notice before changes take effect

Your continued use of the App after changes become effective constitutes acceptance of the modified Terms. If you do not agree to the modified Terms, you should stop using the App and terminate your account.`
    },
    {
      title: "General Provisions",
      content: `**Entire Agreement:** These Terms, together with our Privacy Policy, constitute the entire agreement between you and Poise regarding the App.

**Severability:** If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.

**Waiver:** Our failure to enforce any provision of these Terms shall not be deemed a waiver of such provision or our right to enforce it later.

**Assignment:** You may not assign or transfer your rights under these Terms without our prior written consent. We may assign our rights and obligations without restriction.

**No Agency:** Nothing in these Terms creates a partnership, agency, or employment relationship between you and Poise.`
    },
    {
      title: "Contact Information",
      content: `If you have any questions about these Terms of Service, please contact us:

**Email:** support@trypoise.app
**Website:** https://trypoise.app

For legal notices, please send correspondence to our registered agent or contact us via email with "Legal Notice" in the subject line.`
    }
  ]
};
